
exports.seed = function(knex, Promise) {
  return knex('articles').insert([
    {id: 1, content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet augue rhoncus, tempor felis eu, faucibus mauris. Nam ipsum nunc, euismod non nisi a, porta semper sem. Aenean sed nulla malesuada, tempor justo nec, dapibus massa. Aenean a urna lacinia, iaculis velit eget, vestibulum arcu. Pellentesque eget enim sapien. Sed facilisis ligula at eros pulvinar venenatis. Sed rhoncus, massa sit amet volutpat eleifend, odio lacus convallis tellus, non elementum mi elit nec urna. Integer diam orci, finibus ac sem vulputate, imperdiet molestie ante. Praesent a massa mauris. Integer at placerat orci. Donec vel lacus id dui auctor cursus sed semper elit. In porta vel metus consequat vehicula. Vestibulum nec venenatis nunc. Sed ullamcorper enim vitae laoreet tempus. Aenean vulputate libero non turpis varius, quis vulputate ligula facilisis.

    Sed iaculis mi sed scelerisque tincidunt. Cras malesuada enim vel dapibus condimentum. Curabitur varius pharetra finibus. Donec id lorem nunc. Pellentesque consectetur arcu nunc. Proin suscipit magna vitae odio venenatis posuere. Ut in sapien sed elit convallis ornare sed at nisi. Cras lobortis dictum odio. Quisque porta venenatis justo sit amet euismod. Cras sit amet diam ac eros placerat consequat. Praesent malesuada sapien ligula, in aliquet nunc tincidunt non. Nam ullamcorper dignissim ullamcorper. Proin vitae sem tristique, ullamcorper urna et, viverra velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae sem vehicula, lacinia nunc sit amet, feugiat mi. Vestibulum velit nisl, vehicula at lobortis ut, tempus a turpis.

    Morbi neque urna, rutrum ac pulvinar non, malesuada a felis. Nunc auctor dignissim purus, eu interdum nisl. Phasellus aliquet risus eu pretium volutpat. Fusce sed nisl nec urna consectetur luctus. Mauris tincidunt tellus ornare est accumsan tincidunt. Ut ac suscipit nibh. Nulla luctus ultricies tortor, id vehicula diam mollis ut. Fusce suscipit hendrerit felis non egestas.

    Donec lobortis urna non ultrices ornare. Curabitur rutrum mollis leo, a aliquam ante eleifend eget. Sed posuere facilisis lectus in pretium. Proin ut pulvinar arcu. Vivamus lacinia finibus ligula ac dignissim. Morbi nisl eros, tincidunt quis velit maximus, interdum tempus urna. Maecenas feugiat tortor id dui vehicula fermentum efficitur nec quam. Sed vestibulum cursus justo, id pretium urna congue id. Mauris eu molestie augue. Morbi at diam in orci dictum viverra quis convallis mauris. Sed bibendum est quis mi condimentum facilisis.

    Donec ullamcorper diam eget purus ullamcorper rutrum. Sed non tincidunt tortor. Nunc eget lorem dignissim, varius felis sed, sagittis leo. Nulla at urna lacinia, volutpat diam eget, faucibus risus. Cras tincidunt ipsum et commodo mollis. Praesent purus augue, fringilla eget lacus ut, elementum laoreet nunc. Donec in venenatis lacus. Fusce vel lorem nec nisl pulvinar molestie. Nam imperdiet lobortis ipsum sit amet dapibus. Vivamus bibendum dolor ante, bibendum dictum sem facilisis eu.`, title:'Lorem ipsum dolor',description:'de colores, de clores se visten la campo en la primavera',category:'article', author_id: 1},
    {id: 2, content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet augue rhoncus, tempor felis eu, faucibus mauris. Nam ipsum nunc, euismod non nisi a, porta semper sem. Aenean sed nulla malesuada, tempor justo nec, dapibus massa. Aenean a urna lacinia, iaculis velit eget, vestibulum arcu. Pellentesque eget enim sapien. Sed facilisis ligula at eros pulvinar venenatis. Sed rhoncus, massa sit amet volutpat eleifend, odio lacus convallis tellus, non elementum mi elit nec urna. Integer diam orci, finibus ac sem vulputate, imperdiet molestie ante. Praesent a massa mauris. Integer at placerat orci. Donec vel lacus id dui auctor cursus sed semper elit. In porta vel metus consequat vehicula. Vestibulum nec venenatis nunc. Sed ullamcorper enim vitae laoreet tempus. Aenean vulputate libero non turpis varius, quis vulputate ligula facilisis.

    Sed iaculis mi sed scelerisque tincidunt. Cras malesuada enim vel dapibus condimentum. Curabitur varius pharetra finibus. Donec id lorem nunc. Pellentesque consectetur arcu nunc. Proin suscipit magna vitae odio venenatis posuere. Ut in sapien sed elit convallis ornare sed at nisi. Cras lobortis dictum odio. Quisque porta venenatis justo sit amet euismod. Cras sit amet diam ac eros placerat consequat. Praesent malesuada sapien ligula, in aliquet nunc tincidunt non. Nam ullamcorper dignissim ullamcorper. Proin vitae sem tristique, ullamcorper urna et, viverra velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae sem vehicula, lacinia nunc sit amet, feugiat mi. Vestibulum velit nisl, vehicula at lobortis ut, tempus a turpis.

    Morbi neque urna, rutrum ac pulvinar non, malesuada a felis. Nunc auctor dignissim purus, eu interdum nisl. Phasellus aliquet risus eu pretium volutpat. Fusce sed nisl nec urna consectetur luctus. Mauris tincidunt tellus ornare est accumsan tincidunt. Ut ac suscipit nibh. Nulla luctus ultricies tortor, id vehicula diam mollis ut. Fusce suscipit hendrerit felis non egestas.

    Donec lobortis urna non ultrices ornare. Curabitur rutrum mollis leo, a aliquam ante eleifend eget. Sed posuere facilisis lectus in pretium. Proin ut pulvinar arcu. Vivamus lacinia finibus ligula ac dignissim. Morbi nisl eros, tincidunt quis velit maximus, interdum tempus urna. Maecenas feugiat tortor id dui vehicula fermentum efficitur nec quam. Sed vestibulum cursus justo, id pretium urna congue id. Mauris eu molestie augue. Morbi at diam in orci dictum viverra quis convallis mauris. Sed bibendum est quis mi condimentum facilisis.

    Donec ullamcorper diam eget purus ullamcorper rutrum. Sed non tincidunt tortor. Nunc eget lorem dignissim, varius felis sed, sagittis leo. Nulla at urna lacinia, volutpat diam eget, faucibus risus. Cras tincidunt ipsum et commodo mollis. Praesent purus augue, fringilla eget lacus ut, elementum laoreet nunc. Donec in venenatis lacus. Fusce vel lorem nec nisl pulvinar molestie. Nam imperdiet lobortis ipsum sit amet dapibus. Vivamus bibendum dolor ante, bibendum dictum sem facilisis eu.`, title: 'Southern Optimization',description:'the war of northern agression will lead to Southern optomization',category:'interview', author_id: 1},
    {id: 3, content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet augue rhoncus, tempor felis eu, faucibus mauris. Nam ipsum nunc, euismod non nisi a, porta semper sem. Aenean sed nulla malesuada, tempor justo nec, dapibus massa. Aenean a urna lacinia, iaculis velit eget, vestibulum arcu. Pellentesque eget enim sapien. Sed facilisis ligula at eros pulvinar venenatis. Sed rhoncus, massa sit amet volutpat eleifend, odio lacus convallis tellus, non elementum mi elit nec urna. Integer diam orci, finibus ac sem vulputate, imperdiet molestie ante. Praesent a massa mauris. Integer at placerat orci. Donec vel lacus id dui auctor cursus sed semper elit. In porta vel metus consequat vehicula. Vestibulum nec venenatis nunc. Sed ullamcorper enim vitae laoreet tempus. Aenean vulputate libero non turpis varius, quis vulputate ligula facilisis.

    Sed iaculis mi sed scelerisque tincidunt. Cras malesuada enim vel dapibus condimentum. Curabitur varius pharetra finibus. Donec id lorem nunc. Pellentesque consectetur arcu nunc. Proin suscipit magna vitae odio venenatis posuere. Ut in sapien sed elit convallis ornare sed at nisi. Cras lobortis dictum odio. Quisque porta venenatis justo sit amet euismod. Cras sit amet diam ac eros placerat consequat. Praesent malesuada sapien ligula, in aliquet nunc tincidunt non. Nam ullamcorper dignissim ullamcorper. Proin vitae sem tristique, ullamcorper urna et, viverra velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae sem vehicula, lacinia nunc sit amet, feugiat mi. Vestibulum velit nisl, vehicula at lobortis ut, tempus a turpis.

    Morbi neque urna, rutrum ac pulvinar non, malesuada a felis. Nunc auctor dignissim purus, eu interdum nisl. Phasellus aliquet risus eu pretium volutpat. Fusce sed nisl nec urna consectetur luctus. Mauris tincidunt tellus ornare est accumsan tincidunt. Ut ac suscipit nibh. Nulla luctus ultricies tortor, id vehicula diam mollis ut. Fusce suscipit hendrerit felis non egestas.

    Donec lobortis urna non ultrices ornare. Curabitur rutrum mollis leo, a aliquam ante eleifend eget. Sed posuere facilisis lectus in pretium. Proin ut pulvinar arcu. Vivamus lacinia finibus ligula ac dignissim. Morbi nisl eros, tincidunt quis velit maximus, interdum tempus urna. Maecenas feugiat tortor id dui vehicula fermentum efficitur nec quam. Sed vestibulum cursus justo, id pretium urna congue id. Mauris eu molestie augue. Morbi at diam in orci dictum viverra quis convallis mauris. Sed bibendum est quis mi condimentum facilisis.

    Donec ullamcorper diam eget purus ullamcorper rutrum. Sed non tincidunt tortor. Nunc eget lorem dignissim, varius felis sed, sagittis leo. Nulla at urna lacinia, volutpat diam eget, faucibus risus. Cras tincidunt ipsum et commodo mollis. Praesent purus augue, fringilla eget lacus ut, elementum laoreet nunc. Donec in venenatis lacus. Fusce vel lorem nec nisl pulvinar molestie. Nam imperdiet lobortis ipsum sit amet dapibus. Vivamus bibendum dolor ante, bibendum dictum sem facilisis eu.`, title: 'lachroix sux',description:'this new years try the most famous spinnach lasagana',category:'article', author_id: 4},
    {id: 4, content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam sit amet augue rhoncus, tempor felis eu, faucibus mauris. Nam ipsum nunc, euismod non nisi a, porta semper sem. Aenean sed nulla malesuada, tempor justo nec, dapibus massa. Aenean a urna lacinia, iaculis velit eget, vestibulum arcu. Pellentesque eget enim sapien. Sed facilisis ligula at eros pulvinar venenatis. Sed rhoncus, massa sit amet volutpat eleifend, odio lacus convallis tellus, non elementum mi elit nec urna. Integer diam orci, finibus ac sem vulputate, imperdiet molestie ante. Praesent a massa mauris. Integer at placerat orci. Donec vel lacus id dui auctor cursus sed semper elit. In porta vel metus consequat vehicula. Vestibulum nec venenatis nunc. Sed ullamcorper enim vitae laoreet tempus. Aenean vulputate libero non turpis varius, quis vulputate ligula facilisis.

    Sed iaculis mi sed scelerisque tincidunt. Cras malesuada enim vel dapibus condimentum. Curabitur varius pharetra finibus. Donec id lorem nunc. Pellentesque consectetur arcu nunc. Proin suscipit magna vitae odio venenatis posuere. Ut in sapien sed elit convallis ornare sed at nisi. Cras lobortis dictum odio. Quisque porta venenatis justo sit amet euismod. Cras sit amet diam ac eros placerat consequat. Praesent malesuada sapien ligula, in aliquet nunc tincidunt non. Nam ullamcorper dignissim ullamcorper. Proin vitae sem tristique, ullamcorper urna et, viverra velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae sem vehicula, lacinia nunc sit amet, feugiat mi. Vestibulum velit nisl, vehicula at lobortis ut, tempus a turpis.

    Morbi neque urna, rutrum ac pulvinar non, malesuada a felis. Nunc auctor dignissim purus, eu interdum nisl. Phasellus aliquet risus eu pretium volutpat. Fusce sed nisl nec urna consectetur luctus. Mauris tincidunt tellus ornare est accumsan tincidunt. Ut ac suscipit nibh. Nulla luctus ultricies tortor, id vehicula diam mollis ut. Fusce suscipit hendrerit felis non egestas.

    Donec lobortis urna non ultrices ornare. Curabitur rutrum mollis leo, a aliquam ante eleifend eget. Sed posuere facilisis lectus in pretium. Proin ut pulvinar arcu. Vivamus lacinia finibus ligula ac dignissim. Morbi nisl eros, tincidunt quis velit maximus, interdum tempus urna. Maecenas feugiat tortor id dui vehicula fermentum efficitur nec quam. Sed vestibulum cursus justo, id pretium urna congue id. Mauris eu molestie augue. Morbi at diam in orci dictum viverra quis convallis mauris. Sed bibendum est quis mi condimentum facilisis.

    Donec ullamcorper diam eget purus ullamcorper rutrum. Sed non tincidunt tortor. Nunc eget lorem dignissim, varius felis sed, sagittis leo. Nulla at urna lacinia, volutpat diam eget, faucibus risus. Cras tincidunt ipsum et commodo mollis. Praesent purus augue, fringilla eget lacus ut, elementum laoreet nunc. Donec in venenatis lacus. Fusce vel lorem nec nisl pulvinar molestie. Nam imperdiet lobortis ipsum sit amet dapibus. Vivamus bibendum dolor ante, bibendum dictum sem facilisis eu.`, title:'enchilada',description:'root vegetable medely',category:'video',media:'https://www.youtube.com/watch?v=N1w-hDiJ4dM', author_id: 4}
  ])
  .then(function(){
    return knex.raw("SELECT setval('articles_id_seq', (SELECT MAX(id) FROM articles))")
  })
}
